In [1]:
import pandas as pd
import requests
import wbpy
from pprint import pprint
import json
import csv

In [11]:
wb_us = pd.read_csv("data/worldbank_data3.csv")

In [12]:
wb_us

,Country Name,Country Code,Series Name,Series Code,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,United States,USA,Adjusted savings: carbon dioxide damage (% of ...,NY.ADJ.DCO2.GN.ZS,0.719073406950042,0.740877355957981,0.753016832303031,0.777225237819499,0.777892743732007,0.780214482838623,...,0.839653581364853,0.80722881368102,0.835427008737196,0.842844125624801,0.83110293648313,0.829914958609368,0.831014447399951,0.834013250719056,..,..
1,United States,USA,Adjusted savings: carbon dioxide damage (curre...,NY.ADJ.DCO2.CD,42441797791.0716,45169440199.3682,48460164807.6436,52336544352.2133,55776862236.3717,59098836212.2737,...,132935693084.597,134570298300.203,143492090885.152,152196485271.845,155452127836.113,158058664927.686,164792466829.43,173786235078.31,..,..
2,United States,USA,Agricultural methane emissions (thousand metri...,EN.ATM.METH.AG.KT.CE,172736.823909165,173900.817892833,178039.466145809,179564.558964296,183820.586873406,186398.599399978,...,..,..,..,..,..,..,..,..,..,..
3,United States,USA,Agricultural nitrous oxide emissions (thousand...,EN.ATM.NOXE.AG.KT.CE,153074.76794,153382.00925,159152.58082,159708.82684,166383.90959,164068.07877,...,..,..,..,..,..,..,..,..,..,..
4,United States,USA,CO2 emissions (kg per 2010 US$ of GDP),EN.ATM.CO2E.KD.GD,0.535860382940205,0.536156871634204,0.527441424955003,0.525767414114679,0.512006554779142,0.50239682960545,...,0.346154449370961,0.326459016205428,0.326127579659563,0.321711815755957,0.30680864962596,0.294968151044887,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Last Updated: 10/15/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN